var sqls={
    register:"INSERT INTO `ProEvento`.`User` (`userName`, `password`) VALUES (?, ?);",
    selectUser:'select * from user where userName = ? ',
    loginCheck:"select * from user where userName = ? and password= ? ",
    insertEvent:"INSERT INTO `ProEvento`.`event` ( `title`, `owner`, `description`, `link`,`time`,`category`,`imgPath`) VALUES (?, ?, ?, ?,?,?,?);",
    insertGroup:"INSERT INTO `ProEvento`.`userGroup` ( `name`, `owner`, `description`, `imgPath`,`category`) VALUES (?, ?, ?, ?,?);",
    myEventList:'select * from event where owner=?',
    getEvent:"select * from event where event_id=?",
    getGroup:"select * from userGroup where group_id=?",
    startEvent:"update event set status='Started' where event_id=? AND owner=?",
    endEvent:"update event set status='Completed' where event_id=?",
    updateProfile:"update user set gender=?, profession=?,avtar=?,motto=?,birthday=? where userName=?",
    searchPeople:"select * from user where userName like ?",
    searchGroup:"select * from userGroup where name like ?",
    searchSpecificPeople:"select * from user where userName= ?",
    searchEvent:"select * from event where title like ?",
    searchEventByDate:"select * from event where time like ?",
    followSomeone:"insert into follower (`follow`,`followed`) values (?,?)",
    unFollowSomeone:"delete from follower where follow=? AND followed=?",
    checkFollowStatus:"select * from follower where follow=? AND followed=?",
    getFollowingList:"select * from follower where follow=?",
    getFollowedList:"select * from follower where followed=?",
    checkInvitationStatus:"select * from invitation where event_id=? AND invited_user=?",
    inviteSomeone:"insert into invitation (`event_id`,`invited_user`) values(?,?)",
    requestToJoin:"insert into join_request (`join_group`,`userName`) values(?,?)",
    deleteRequest:"delete from join_request  where join_group=? AND userName=?",
    unInviteSomeone:"delete from invitation where event_id=? AND invited_user=?",
    inviteSomeoneGroup:"insert into group_member (`group_id`,`userName`) values(?,?)",
    unInviteSomeoneGroup:"delete from group_member where group_id=? AND userName=?",
    checkGroupStatus:"select * from group_member where group_id=? AND userName=?",
    getInvitedList:"select * from invitation where event_id=?",
    deactivaeSomeone:"update user set deactivated=1 where userName=?",
    activateSomeone:"update user set deactivated=0 where userName=?",
    getGroupList:'select * from userGroup where owner = ?',
    getMemberList:"select * from group_member where group_id=?",
    getRequestList:"select * from join_request where join_group=?",
    addHashtag:"insert into event_hashtag (`event_id`,`hashtag`) values(?,?)",
    getAllHashtag:"select * from event_hashtag where event_id=?",
    searchHashtag:"select * from event_hashtag where hashtag=?",
}
module.exports=sqls